### PR TITLE
Consistency across awards

### PR DESCRIPTION
**Pull request by superic**
Matches grant-pattishall-award.com and smith-pintado-award.com layout

@jeremyruppel?

### CODE REVIEW

**Comment by pdokas** [comment]
(this was bugging me too)

**Comment by superic** [comment]
Dammit, @pdokas, don't look at these PRs.

**Comment by jeremyruppel** [comment]
Love it :shipit:

**Comment by pdokas** [comment]
_\*watches everything\*_

**Comment by mroth** [comment]
Can you resolve the merge conflict so I can merge this from web interface please?

**Comment by pdokas** [comment]
@superic…

**Comment by alex-seville** [comment]
@superic bump

**Comment by pdokas** [comment]
This can be closed with https://github.com/mroth/bogan-martin-award/pull/7

**Pull request closed without merging**
